import { Language } from "./types";

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.menu": "Menu",
    "nav.about": "Location & Contact",
    "nav.admin": "Admin Panel",
    "nav.switchLanguage": "Shqip",
    "nav.orderNow": "Call to Order",

    // Hero
    "hero.title": "Authentic Romana Pizza in Tirana",
    "hero.subtitle": "Freshly baked artisan sourdough pizzas prepared with traditional Italian recipes and the finest local ingredients.",
    "hero.viewMenu": "Explore Our Menu",
    "hero.adminMode": "Configure Menu",
    "hero.rating": "4.6 rating out of 40 local reviews",
    "hero.statusOpen": "Open • Closes 11:00 PM",
    "hero.statusClosed": "Closed • Opens 11:00 AM",

    // Pizza info & About
    "about.title": "Romana Pizza Tirana",
    "about.description": "Located on Rruga Ëngjëll Marashi in the heart of Tirana, Romana Pizza offers an unforgettable dining experience. Enjoy our award-winning pizzas crafted by master pizzaiolos, freshly made starters, and delightful Italian desserts in a cozy family-owned atmosphere.",
    "about.workingHours": "Opening Hours",
    "about.hoursValue": "Monday - Saturday: 11:00 AM - 11:00 PM (Sunday Closed)",
    "about.phone": "Phone Number",
    "about.address": "Address",
    "about.addressValue": "Rruga Ëngjëll Marashi, Tiranë 1052, Albania",
    "about.neighborhood": "Neighborhood Code",
    "about.findUs": "Find Us on Google Maps",
    "about.directions": "Get Directions",
    "about.history": "Your Maps History",
    "about.historyValue": "Romana Pizza is in your Tirana culinary registry.",

    // Reviews Section
    "reviews.title": "Guest Experiences",
    "reviews.subtitle": "Highly rated by locals and tourists alike with 4.6/5 stars",
    "reviews.writeReview": "Share Your Experience",
    "reviews.reviewsCount": "Based on 40 Google Reviews",
    "reviews.reviewer1": "Arben Hoxha",
    "reviews.comment1": "The best Roman style pizza in Tirana! The thin crust sourdough is crispy and the ingredients are extremely fresh. Highly recommend the Diavola!",
    "reviews.reviewer2": "Sarah Miller",
    "reviews.comment2": "What a beautiful little gem in Albania! Super friendly staff, very reasonable prices, and the Tiramisu is absolutely divine.",
    "reviews.reviewer3": "Elora Krasniqi",
    "reviews.comment3": "Incredible sourdough base! Fast service and amazing vibe. They really care about the quality of the ingredients.",

    // Categories
    "cat.all": "All Delicious Bites",
    "cat.pizza": "Artisan Pizzas",
    "cat.sandwich": "Gourmet Sandwiches",
    "cat.salad": "Fresh Salads",
    "cat.pasta": "Pastas & Spaghetti",
    "cat.calzone": "Baked Calzones",
    "cat.traditional": "Traditional & Plates",
    "cat.drink": "Cold Drinks",
    "cat.dessert": "House Desserts",
    "cat.appetizer": "Appetizers & Starters",

    // Menu section general
    "menu.title": "Our Culinary Craft",
    "menu.subtitle": "Everything is freshly prepared. Please select a category below.",
    "menu.vegetarian": "Vegetarian",
    "menu.spicy": "Spicy",
    "menu.allLek": "ALL",
    "menu.priceConvert": "Convert Euro",
    "menu.priceInEuro": "approx.",
    "menu.outOfStock": "Temporarily Sold Out",
    "menu.noItems": "No items in this category yet. Visited the Admin Panel to install culinary delights!",
    "menu.callToOrder": "Call to order: +355 69 688 5195",
    "menu.badgeItem": "item",
    "menu.badgeItems": "items",

    // Admin Dashboard
    "admin.title": "Romana Pizza Controller Dashboard",
    "admin.subtitle": "Configure and update restaurant menu items in real-time. Changes apply instantly to English & Albanian clients.",
    "admin.accessTitle": "System Administrator Authentication",
    "admin.accessPrompt": "Please enter your PIN code to access the secure menu database controller:",
    "admin.accessPlaceholder": "Enter 7-digit PIN",
    "admin.accessButton": "Unlock Console",
    "admin.errPin": "The entry PIN is incorrect. Please enter the valid 7-digit administrator code.",
    "admin.locked": "Security Engine Loaded",
    "admin.unlocked": "Authorized Session Active",
    "admin.addItem": "Add Custom Menu Item",
    "admin.editItem": "Update Selected Item",
    "admin.cancel": "Cancel Configuration",
    "admin.saveItem": "Save to Menu Database",
    "admin.deleteItem": "Remove permanently",
    "admin.confirmDelete": "Are you absolutely sure you want to delete this menu item?",
    "admin.lblCategory": "Menu Category Selection",
    "admin.lblNameEn": "Item Name (English translation)",
    "admin.lblNameSq": "Item Name (Albanian translation)",
    "admin.lblPrice": "Sales Price (in Albanian ALL)",
    "admin.lblDescEn": "Rich Description (English)",
    "admin.lblDescSq": "Rich Description (Albanian)",
    "admin.lblImage": "Display Image URL",
    "admin.imgPlaceholder": "Select a category preset or paste custom Unsplash link",
    "admin.lblAvailable": "Stock Status (Is Available now)",
    "admin.lblVeg": "Dietary (Is Vegetarian)",
    "admin.lblSpicy": "Dietary (Is Spicy)",
    "admin.statusSuccess": "Action saved successfully! Database synced.",
    "admin.statusError": "Error syncing action. Please call engineering.",
    "admin.quickPresets": "Quick Image Presets:",
    "admin.presetPizza1": "Classic Pizza slice",
    "admin.presetPizza2": "Premium Woodfired",
    "admin.presetDessert": "Rich Chocolate/Cream",
    "admin.presetDrink": "Chilled beverage",
    "admin.activeItemsCount": "active items listed",
    "admin.logout": "Lock Console",

    // General
    "footer.rights": "All rights reserved. Styled on Italian artisan heritage.",
    "footer.tagline": "Bringing Roman flavor to Tirana since 2018.",
    "footer.visitUs": "Visit Us"
  },
  sq: {
    // Navbar
    "nav.home": "Ballina",
    "nav.menu": "Menuja",
    "nav.about": "Vendndodhja & Kontakti",
    "nav.admin": "Paneli i Adminit",
    "nav.switchLanguage": "English",
    "nav.orderNow": "Telefono për Porosi",

    // Hero
    "hero.title": "Pica Romana Autentike në Tiranë",
    "hero.subtitle": "Pica artizanale të pjekura rishtas me brumë të thartë (sourdough), të përgatitura sipas recetave tradicionale italiane dhe përbërësve më të mirë vendas.",
    "hero.viewMenu": "Eksploro Menunë Tonë",
    "hero.adminMode": "Konfiguro Menunë",
    "hero.rating": "Vlerësimi 4.6 nga 40 rishikime lokale",
    "hero.statusOpen": "Hapur • Mbyllet në 11:00 PM",
    "hero.statusClosed": "Mbyllur • Hapet në 11:00 AM",

    // Pizza info & About
    "about.title": "Romana Pizza Tiranë",
    "about.description": "E vendosur në Rrugën Ëngjëll Marashi në zemër të Tiranës, Romana Pizza ofron një përvojë të paharrueshme kulinare. Shijoni picat tona të vlerësuara me çmime të krijuara nga pizzaiolos mjeshtër, mezet e freskëta dhe ëmbëlsirat e këndshme italiane në një atmosferë të rehatshme familjare.",
    "about.workingHours": "Orari i Punës",
    "about.hoursValue": "E Hënë - E Shtunë: 11:00 AM - 11:00 PM (E Diel Mbyllur)",
    "about.phone": "Numri i Telefonit",
    "about.address": "Adresa",
    "about.addressValue": "Rruga Ëngjëll Marashi, Tiranë 1052, Shqipëri",
    "about.neighborhood": "Kodi i Lagjes",
    "about.findUs": "Na Gjeni në Google Maps",
    "about.directions": "Merrni Drejtimet",
    "about.history": "Historiku Juaj në Harta",
    "about.historyValue": "Romana Pizza është në regjistrin tuaj kulinar të Tiranës.",

    // Reviews Section
    "reviews.title": "Përvojat e Mysafirëve",
    "reviews.subtitle": "E vlerësuar lart nga vendasit dhe turistët me 4.6/5 yje",
    "reviews.writeReview": "Ndani Përvojën Tuaj",
    "reviews.reviewsCount": "Bazuar në 40 Rishikime në Google",
    "reviews.reviewer1": "Arben Hoxha",
    "reviews.comment1": "Pica më e mirë e stilit romak në Tiranë! Brumi i thartë (sourdough) me petë të hollë është krokant dhe përbërësit janë jashtëzakonisht të freskët. Rekomandoj shumë Pica Diavola!",
    "reviews.reviewer2": "Sarah Miller",
    "reviews.comment2": "Çfarë xhevahiri i vogël i bukur në Shqipëri! Staf super miqësor, çmime shumë të arsyeshme dhe Tiramisuja është absolutisht hyjnore.",
    "reviews.reviewer3": "Elora Krasniqi",
    "reviews.comment3": "Bazë e mrekullueshme me brumë të thartë! Shërbim i shpejtë dhe atmosferë fantastike. Ata vërtet kujdesen për cilësinë e përbërësve.",

    // Categories
    "cat.all": "Të Gjitha Ushqimet",
    "cat.pizza": "Pica Artizanale",
    "cat.sandwich": "Sanduiçë Gourmet",
    "cat.salad": "Sallata të Freskëta",
    "cat.pasta": "Pasta & Spageti",
    "cat.calzone": "Kalcone të Pjekura",
    "cat.traditional": "Tradicionale & Pjata",
    "cat.drink": "Pije të Ftohta",
    "cat.dessert": "Ëmbëlsira Shtëpie",
    "cat.appetizer": "Paraushqime & Meze",

    // Menu section general
    "menu.title": "Arti Ynë Kulinar",
    "menu.subtitle": "Çdo gjë përgatitet e freskët. Ju lutemi zgjidhni një kategori më poshtë.",
    "menu.vegetarian": "Vegjetariane",
    "menu.spicy": "Pikante",
    "menu.allLek": "ALL",
    "menu.priceConvert": "Konverto Euro",
    "menu.priceInEuro": "afërsisht",
    "menu.outOfStock": "E shitur përkohësisht",
    "menu.noItems": "Nuk ka ende artikuj në këtë kategori. Vizitoni Panelin e Adminit për të shtuar artikuj të shijshëm!",
    "menu.callToOrder": "Telefono për porosi: +355 69 688 5195",
    "menu.badgeItem": "artikull",
    "menu.badgeItems": "artikuj",

    // Admin Dashboard
    "admin.title": "Paneli i Kontrollit Romana Pizza",
    "admin.subtitle": "Konfiguro dhe përditëso artikujt e menusë së restorantit në kohë reale. Ndryshimet aplikohen menjëherë për klientët në Anglisht dhe Shqip.",
    "admin.accessTitle": "Autentikimi i Administratorit të Sistemit",
    "admin.accessPrompt": "Ju lutemi vendosni kodin PIN për të hyrë në kontrolluesin e sigurt të menusë:",
    "admin.accessPlaceholder": "Shkruani PIN-in me 7 shifra",
    "admin.accessButton": "Shkyç Konsolën",
    "admin.errPin": "Kodi PIN është i pasaktë. Ju lutem vendosni kodin e saktë me 7 shifra të administratorit.",
    "admin.locked": "Mbrojtja e Sigurisë e Ngarkuar",
    "admin.unlocked": "Seanca e Autorizuar Aktivizuar",
    "admin.addItem": "Shto Artikull të Ri",
    "admin.editItem": "Përditëso Artikullin e Zgjedhur",
    "admin.cancel": "Anulo",
    "admin.saveItem": "Ruaj në Databazën e Menusë",
    "admin.deleteItem": "Fshi përgjithmonë",
    "admin.confirmDelete": "A jeni absolutisht i sigurt që dëshironi ta fshini këtë artikull të menusë?",
    "admin.lblCategory": "Zgjedhja e Kategorisë",
    "admin.lblNameEn": "Emri i Artikullit (Anglisht)",
    "admin.lblNameSq": "Emri i Artikullit (Shqip)",
    "admin.lblPrice": "Çmimi i Shitjes (në Lek)",
    "admin.lblDescEn": "Përshkrimi i Detajuar (Anglisht)",
    "admin.lblDescSq": "Përshkrimi i Detajuar (Shqip)",
    "admin.lblImage": "URL e Imazhit",
    "admin.imgPlaceholder": "Zgjidhni një pamje standarde ose vendosni një URL të Unsplash",
    "admin.lblAvailable": "Statusi i Stokut (Hapur për shitje)",
    "admin.lblVeg": "Dietike (Vegjetariane)",
    "admin.lblSpicy": "Dietike (Pikante)",
    "admin.statusSuccess": "Veprimi u ruajt me sukses! Databaza u sinkronizua.",
    "admin.statusError": "Gabim gjatë ruajtjes. Ju lutem kontaktoni inxhinierinë.",
    "admin.quickPresets": "Imazhe të Shpejta:",
    "admin.presetPizza1": "Fetë pice klasike",
    "admin.presetPizza2": "Piceri klasike",
    "admin.presetDessert": "Ëmbëlsirë me krem",
    "admin.presetDrink": "Pije freskuese",
    "admin.activeItemsCount": "artikuj aktivë të listuar",
    "admin.logout": "Kyç Konsolën",

    // General
    "footer.rights": "Të gjitha të drejtat të rezervuara. Stiluar mbi trashëgiminë artizanale italiane.",
    "footer.tagline": "Sjellim shijen e Romës në Tiranë që nga viti 2018.",
    "footer.visitUs": "Na Vizitoni"
  }
};
